// Package timerpi holds the TimerPi domain model, SQLite persistence and the
// cue engine (PROTOCOL.md §Domain/§Engine). The package is pure domain: no
// HTTP, WS or template imports — IO lives at the edges (routes/ws/mesh/drm).
package timerpi

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// Cue row kinds (cues.kind).
const (
	KindSession = "session" // a timed session in the running order
	KindBreak   = "break"   // break / changeover / host slot (ordinary cue row)
)

// Per-cue timer styles (cues.timer_kind).
const (
	TimerCountdown = "COUNTDOWN" // counts down to zero (default)
	TimerCountStop = "COUNTSTOP" // counts up like a stopwatch; operator stops it
	TimerClock     = "CLOCK"     // wall clock; the engine does no cue timing
)

// What happens when a countdown crosses zero (cues.end_action).
const (
	EndHold     = "HOLD"     // freeze at 00:00 and hold (default)
	EndOvertime = "OVERTIME" // keep counting up; remaining goes negative
	EndBlank    = "BLANK"    // hide the countdown; show blank + scheduled end
)

// Alert states for the active cue (snapshot runtime.alertState / timer frame).
const (
	AlertNone = 0
	Alert1    = 1 // remaining <= Alert1MS
	Alert2    = 2 // remaining <= Alert2MS (deepest)
)

// Default alert colours (matches the PROTOCOL example).
const (
	DefaultAlertColor1 = "#ffaa00"
	DefaultAlertColor2 = "#ff4444"
)

// DefaultRate is the countdown rate multiplier default (1 s per second).
const DefaultRate = 1.0

// KnownTags is the suggested tag vocabulary; tags are free-form text but the
// UI offers these (PLAN §2: VT/GFX/COM/CAM/PRES…).
var KnownTags = []string{"VT", "GFX", "COM", "CAM", "PRES"}

// colorRe accepts CSS hex colours only (#rgb/#rgba/#rrggbb/#rrgbbaa) — same
// rule as CuTePi's ValidColor; values reach style attributes and must never
// carry anything else.
var colorRe = regexp.MustCompile(`^#([0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$`)

// ValidColor reports whether s is empty (no colour) or a CSS hex colour.
func ValidColor(s string) bool {
	return s == "" || colorRe.MatchString(s)
}

// Show is one day's running order.
type Show struct {
	ID        int64  `db:"id"         json:"id"`
	Title     string `db:"title"      json:"title"`
	CreatedAt int64  `db:"created_at" json:"createdAt"`
	UpdatedAt int64  `db:"updated_at" json:"updatedAt"`
	// Zone is the event-grouping label (proposal #3): shows sharing a zone
	// appear as rooms on the /zone/<name> walk-in/event display. Empty = no
	// event grouping (single-show use stays unaffected).
	Zone string `db:"zone" json:"zone"`
	// Code is the public, shareable, unique 8-character share code
	// (ALPHANUMERIC Crockford-style base32, stored bare, displayed 4-4 →
	// timerpi/gen.go is the rulebook). Empty only mid-migration reads.
	Code string `db:"code" json:"code"`
	// Passphrase is the OPTIONAL per-show extra password (privacy tier):
	// when set, the operator + display pages and WS joins for this show
	// require the show unlock cookie (or join token). Never serialized to
	// clients — snapshot marshallings must not leak it.
	Passphrase string `db:"passphrase" json:"-"`
	// Notes is the operator's free-text day memo (A7): shown on the
	// dashboard panel, the printable daysheet and stage footer. Operator
	// content, not a secret — travels in snapshots like the title.
	Notes string `db:"notes" json:"notes"`
	// DayStart is the SCHEDULED day start "HH:MM" (B4): when set, the
	// engine auto-anchors dayStartTS there on boot/first use instead of
	// leaving the day unanchored until the operator taps.
	DayStart string `db:"day_start" json:"dayStart"`
	// Blanked is the GLOBAL display blackout (E3): when true every
	// display surface (/d/ stage + variants + board, HDMI renderer)
	// shows black + STANDBY instead of the running order. Operator
	// state, not a secret — rides snapshots like notes so all screens
	// flip together.
	Blanked bool `db:"blanked" json:"blanked"`
	// EventID is the parent event: a show IS a room of that event
	// (PRODUCT §2). RoomPos orders rooms inside the event.
	EventID int64 `db:"event_id" json:"eventId"`
	RoomPos int64 `db:"room_pos" json:"roomPos"`
	// RoomPW is the optional moderator password hash (HashPassword); never
	// serialized.
	RoomPW string `db:"room_pw" json:"-"`
}

// Normalize canonicalizes show-typed data: the title is trimmed, the code
// uppercased (and trimmed of whitespace; the alphabet is case-insensitive
// on input but stored uppercase so `SHOW.code` reads and sorts canonically).
// Codes are GENERATED by gen.go — creations never pass one in.
func (s *Show) Normalize() {
	s.Title = strings.TrimSpace(s.Title)
	s.Code = strings.ToUpper(strings.TrimSpace(s.Code))
}

// Validate checks operator-entered show data.
func (s Show) Validate() error {
	if strings.TrimSpace(s.Title) == "" {
		return fmt.Errorf("timerpi: show title must not be empty")
	}
	return nil
}

// ClampRate bounds a rate multiplier into the ×0.5–×2.0 display contract// (PROTOCOL §commands); any sane automation caller or stray script gets a
// stable bound instead of a re-anchor math break. Used by the REST cmd
// alias (B5); the WS path keeps raw operator intent.
func ClampRate(r float64) float64 {
	if r < 0.5 {
		return 0.5
	}
	if r > 2.0 {
		return 2.0
	}
	return r
}

// DayStartTSFrom maps a stored "HH:MM" (B4) onto TODAY (local time) from a
// now-instant: "" / garbage → 0 (no anchor from the setting); a bad clock
// never anchors. Late days stay where the operator's manual anchor put
// them — the caller decides freshness policy (engines re-anchor only when
// no explicit anchor exists).
func DayStartTSFrom(hhmm string, nowMS int64) int64 {
	hhmm = strings.TrimSpace(hhmm)
	parts := strings.Split(hhmm, ":")
	if len(parts) != 2 {
		return 0
	}
	h, err1 := strconv.Atoi(parts[0])
	m, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil || h < 0 || h > 23 || m < 0 || m > 59 {
		return 0
	}
	t := time.UnixMilli(nowMS).Local()
	return time.Date(t.Year(), t.Month(), t.Day(), h, m, 0, 0, t.Location()).UnixMilli()
}

// ClockAt resolves a wall-clock "HH:MM" inside the room's day (midnight
// handling, STATUS: owner 2026-10-06; BUGLOG RW25). With a day anchor it is
// that day's date at HH:MM, or the NEXT date when HH:MM is earlier than the
// anchor: a day starting 18:00 runs 23:30, then 00:15 tomorrow. With no
// anchor it is today's HH:MM (DayStartTSFrom). 0 for a bad time. Calendar
// arithmetic (AddDate) keeps DST days right.
func ClockAt(hhmm string, dayStartTS, nowMS int64) int64 {
	if dayStartTS == 0 {
		return DayStartTSFrom(hhmm, nowMS)
	}
	ts := DayStartTSFrom(hhmm, dayStartTS)
	if ts == 0 {
		return 0
	}
	if ts < dayStartTS {
		ts = time.UnixMilli(ts).Local().AddDate(0, 0, 1).UnixMilli()
	}
	return ts
}

// Cue is one row of the running order. Pos is the stable visual/run order
// (1-based, contiguous); ID is the stable row identity used by reorder ops.
type Cue struct {
	ID           int64  `db:"id"            json:"id"`
	ShowID       int64  `db:"show_id"       json:"showId,omitempty"`
	Pos          int64  `db:"pos"           json:"pos"`
	Label        string `db:"label"         json:"label"`
	DurationMS   int64  `db:"duration_ms"   json:"durationMS"`
	Kind         string `db:"kind"          json:"kind"` // session | break
	Tags         string `db:"tags"          json:"tags"` // "VT GFX" style free text
	Speaker      string `db:"speaker"       json:"speaker"`
	HoldMS       int64  `db:"hold_ms"       json:"holdMS"` // deliberate changeover/buffer
	TimerKind    string `db:"timer_kind"    json:"timerKind"`
	Alert1MS     int64  `db:"alert1_ms"     json:"alert1MS"` // 0 = no threshold
	Alert2MS     int64  `db:"alert2_ms"     json:"alert2MS"` // 0 = no threshold
	AlertColor1  string `db:"alert_color1"  json:"alertColor1"`
	AlertColor2  string `db:"alert_color2"  json:"alertColor2"`
	EndAction    string `db:"end_action"    json:"endAction"`
	AutoContinue bool   `db:"autocontinue"  json:"autoContinue"`
	Notes        string `db:"notes"         json:"notes"`
	Color        string `db:"color"         json:"color"`
	// StartAt is the wall-clock auto-start "HH:MM" (E5, "" = off): the
	// engine starts this cue once the time comes, but only while nothing
	// is running or paused (hand operation always wins; no yanking live
	// cues, no refires — firing advances ActivePos past the cue).
	StartAt string `db:"start_at" json:"startAt,omitempty"`
	// Location is where a break happens ("Great Hall": coffee, lunch); it
	// shows on schedules (STATUS U14). Free text, 80 chars.
	Location string `db:"location" json:"location,omitempty"`
	// UpdatedAt is the row's last-write stamp. It rides the wire cue object
	// (docs/OFFLINE-EDIT.md) so an offline mesh master can merge per cue on
	// reconnect; snapshot readers that predate it simply ignore the field.
	UpdatedAt int64 `db:"updated_at" json:"updatedAt,omitempty"`
	// Day is the event day this session belongs to (1-based). v2 events
	// are single-day, so it is always 1; the column keeps the model ready
	// for multi-day events (PRODUCT §4.7).
	Day int64 `db:"day" json:"day,omitempty"`
}

// Normalize applies defaults and clamps in place: empty kinds fall back to
// session/COUNTDOWN/HOLD, alert colours to the defaults, negatives to 0.
// Schedule math and the engine depend on these invariants holding.
func (c *Cue) Normalize() {
	if c.Kind == "" {
		c.Kind = KindSession
	}
	c.Location = ClipUTF8(strings.TrimSpace(c.Location), 80)
	if c.TimerKind == "" {
		c.TimerKind = TimerCountdown
	}
	if c.EndAction == "" {
		c.EndAction = EndHold
	}
	if c.AlertColor1 == "" {
		c.AlertColor1 = DefaultAlertColor1
	}
	if c.AlertColor2 == "" {
		c.AlertColor2 = DefaultAlertColor2
	}
	if c.DurationMS < 0 {
		c.DurationMS = 0
	}
	if c.HoldMS < 0 {
		c.HoldMS = 0
	}
	if c.Alert1MS < 0 {
		c.Alert1MS = 0
	}
	if c.Alert2MS < 0 {
		c.Alert2MS = 0
	}
	c.Label = strings.TrimSpace(c.Label)
}

// MaxDurationMS caps every cue duration, hold and alert: 7 days. Larger
// values overflow the schedule maths (on the Pi's arm64 a huge float
// saturates to MaxInt64 and times go negative; BUGLOG RW30).
const MaxDurationMS int64 = 7 * 24 * 3600 * 1000

// Validate checks the enum-ish fields and non-negative magnitudes. Alert
// thresholds are independent (alert1 = 0 means "no first alert"), so alert2
// may be set while alert1 is not.
func (c Cue) Validate() error {
	switch c.Kind {
	case KindSession, KindBreak:
	default:
		return fmt.Errorf("timerpi: cue kind %q invalid (want %q or %q)", c.Kind, KindSession, KindBreak)
	}
	for _, f := range []struct {
		name string
		ms   int64
	}{{"duration", c.DurationMS}, {"hold", c.HoldMS}, {"alert1", c.Alert1MS}, {"alert2", c.Alert2MS}} {
		if f.ms > MaxDurationMS {
			return fmt.Errorf("timerpi: cue %s %d ms is longer than 7 days", f.name, f.ms)
		}
	}
	switch c.TimerKind {
	case TimerCountdown, TimerCountStop, TimerClock:
	default:
		return fmt.Errorf("timerpi: cue timerKind %q invalid", c.TimerKind)
	}
	switch c.EndAction {
	case EndHold, EndOvertime, EndBlank:
	default:
		return fmt.Errorf("timerpi: cue endAction %q invalid", c.EndAction)
	}
	if c.DurationMS < 0 || c.HoldMS < 0 || c.Alert1MS < 0 || c.Alert2MS < 0 {
		return fmt.Errorf("timerpi: cue %q has a negative duration/hold/alert", c.Label)
	}
	if !ValidColor(c.AlertColor1) || !ValidColor(c.AlertColor2) || !ValidColor(c.Color) {
		return fmt.Errorf("timerpi: cue %q has an invalid colour", c.Label)
	}
	if c.StartAt != "" && DayStartTSFrom(c.StartAt, time.Now().UnixMilli()) == 0 {
		return fmt.Errorf("timerpi: cue %q startAt must be HH:MM 00:00-23:59", c.Label)
	}
	return nil
}

// Message is a stage overlay line ("PLEASE WRAP UP!"). ShownAt = 0 hides it;
// > 0 (epoch ms) marks it shown and orders multiple shown overlays.
type Message struct {
	ID      int64  `db:"id"       json:"id"`
	ShowID  int64  `db:"show_id"  json:"showId,omitempty"`
	Text    string `db:"text"     json:"text"`
	Color   string `db:"color"    json:"color"`
	ShownAt int64  `db:"shown_at" json:"shownAt"`
	// UpdatedAt is row bookkeeping for the snapshot stamp; not on the wire.
	UpdatedAt int64 `db:"updated_at" json:"-"`
}

func (m *Message) Normalize() {
	m.Text = strings.TrimSpace(m.Text)
	if !ValidColor(m.Color) {
		m.Color = ""
	}
}

func (m Message) Validate() error {
	if strings.TrimSpace(m.Text) == "" {
		return fmt.Errorf("timerpi: message text must not be empty")
	}
	if !ValidColor(m.Color) {
		return fmt.Errorf("timerpi: message colour %q invalid", m.Color)
	}
	return nil
}

// Runtime is the per-show engine state (one row keyed by show). All epoch
// times are milliseconds. AnchorTS is the wall-clock instant the active cue
// started; PausedElapsedMS is the scaled elapsed frozen at pause (or at a
// rate re-anchor). EndAction mirrors the active cue's end action so clients
// can render HOLD/OVERTIME/BLANK without re-reading cues.
type Runtime struct {
	ShowID          int64   `db:"show_id"          json:"showId"`
	ActivePos       int64   `db:"active_pos"       json:"activePos"` // 0 = none
	PrevPos         int64   `db:"prev_pos"         json:"prevPos"`   // 0 = none
	NextPos         int64   `db:"next_pos"         json:"nextPos"`   // 0 = none
	Paused          bool    `db:"paused"           json:"paused"`
	Running         bool    `db:"running"          json:"running"`
	EndAction       string  `db:"end_action"       json:"endAction"`
	AnchorTS        int64   `db:"anchor_ts"        json:"anchorTS"` // 0 = idle/armed
	Rate            float64 `db:"rate"             json:"rate"`     // default 1.0
	PausedElapsedMS int64   `db:"paused_elapsed_ms" json:"pausedElapsedMS"`
	DayStartTS      int64   `db:"day_start_ts"      json:"dayStartTS"` // schedule/day-bar anchor
	// UpdatedAt is row bookkeeping for the snapshot stamp; not on the wire.
	UpdatedAt int64 `db:"updated_at" json:"-"`
}
